/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lucasmreis' at '9/2/14 9:22 PM' with Gradle 2.0
 *
 * @author lucasmreis, @date 9/2/14 9:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
